spring:
    profiles:
      group:
        dev: dev
        qa: qa
        live: live
    application:
      name: hanghae-excercise


---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: qa

server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: live

server:
  port: 8083

